### ISSUE TITLE
[0.8][styling] Should be able to mixin sibling properties

### ISSUE THREAD

**Issue by nevir** [Polymer/polymer#1399]
Given styles:
```css
* {
  --base-stuff: { color: white; }
  --pretty-things: {
    mixin(--base-stuff);
    background-color: red;
  }

  .foo {
    mixin(--pretty-things);
  }
}
```

I would expect a `<div class="foo">` to be red w/ white text, but currently it appears that the `mixin(--base-stuff)` is not inherited.
