### ISSUE TITLE
[0.8][styling] Want to define custom variables in the same scope as their references 

### ISSUE THREAD

**Issue by morethanreal** [Polymer/polymer#1406]
I want to give a custom element a default color from the shared theme while allowing a hook for the user to customize the color by doing this:

```css
* {
  --my-element-background-color: var(--my-theme-background-color);
}

:host {
  background-color: var(--my-element-background-color);
}
```

It seems like the variable definition must be in a different scope than the reference to the variable.
