### ISSUE TITLE
Issues with Safari and "enableCustomStyleProperties: true".

### ISSUE THREAD

**Issue by mdwragg** [Polymer/polymer#1432]
Getting a few issues with Safari and component 'theming' turned on via the ```enableCustomStyleProperties``` flag.

I'll list the CSS selectors that Safari is failing to deal with below:

```css
  input[type="number"]::-webkit-inner-spin-button,
  input[type="number"]::-webkit-outer-spin-button {
    height: auto;
  }
```
```css
input[type="search"]::-webkit-search-cancel-button,
  input[type="search"]::-webkit-search-decoration {
    -webkit-appearance: none;
  }
```

I'm trapping the error in shady.html in the following section:

```js
      // This is a polyfill for Element.prototype.matches, which is sometimes
      // still prefixed. Alternatively we could just polyfill it somewhere.
      // Note that the arguments are reversed from what you might expect.
      elementMatches: function(selector, node) {
        if (node === undefined) {
          node = this;
        }
        return matchesSelector.call(node, selector);   //error happening here...
      },
```
This is happening in Polymer 0.8 RC4.

Thanks!
