### ISSUE TITLE
Default values for custom variables 

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer#1543]
If you have a default value for a custom variable that contains parenthesis, the regexp for detecting variables stops working.
Here's a use case:
```css
 background-color: var(---default-color, rgba(0, 0, 0, 0.5));
```

The regexp thinks that the closing parenthesis is the first `)` I wonder if there's a solution using regexp for dealing with recursion.
The workaround is to have a 
```css
:root { 
   ---default-color:  rgba(0, 0, 0, 0.5);
}
```

**Comment by kevinpschaaf** [comment]
Another short-term option would be this:

```css
:host {
  --default-default-color: rgba(0, 0, 0, 0.5);
}

... {
  background-color: var(--default-color, --default-default-color);
}
```

We will work on this; it's a limitation to the current parsing techniques being used.
