### ISSUE TITLE
::content styling rule should have higher specificity than the distributed element's :host rule

### ISSUE THREAD

**Issue by morethanreal** [Polymer/polymer#1598]
If `<x-foo>` has this style:

``` css
:host {
  color: blue;
}
```

And `<x-bar>` has this style:

``` css
:host > :content > * {
  color: red;
}
```

When `<x-foo>` is distributed into `<x-bar>` I expect the `<x-foo>` to be red, but it is blue. I can work around this by using a wrapper element around the `<content>` in `<x-bar>`, which makes the `::content` rule more specific.
