### ISSUE TITLE
Property values that contain a `:` inside a mixin.

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer#1623]
In a mixin, when you have a property which value contains a `:`, similar to:
```css
:host {
    --paper-scroll-header-panel-full-header: {
        background-image: url(http://google.com/image.png);
    };
}
```
is converted to `background-image: url(http:%20%20//google.com/image.png);`

Reported in https://github.com/PolymerElements/paper-scroll-header-panel/issues/4
