### ISSUE TITLE
styling: using var() splits a rule in two with different specificities, causes problems with shorthands

### ISSUE THREAD

**Issue by justinfagnani** [Polymer/polymer#1761]
```css
* {
  --border-color: blue;
}
foo {
  border: solid var(--border-color);
  border-width: 1px 0;
}
```

gets split into:

```css
.my-host-0 foo.my-host {
  border: solid blue;
}
foo.my-host {
  border-width: 1px 0;
}
```

Because `.my-host-0 foo.my-host` has higher specificity than `foo.my-host` the `border-width` property is overridden by the shorthand `border` property. In this example this results in the border width being the default from the user style sheet (3px).
