### ISSUE TITLE
Incorrect style for custom CSS properties when extending a native element

### ISSUE THREAD

**Issue by Sleeckx** [Polymer/polymer#1807]
I presume the button in the following code snippet should have a red background? Not entirely sure if this should work like this: http://jsbin.com/jewatuvoyo/1/edit?html,output

There's a space between the classname and the attribute selector in the style that causes this :
```css
.x-test-0 [is=x-test] {
  background-color:red;
}
```
