### ISSUE TITLE
Style shim only converts a single ::shadow or /deep/ in a selector

### ISSUE THREAD

**Issue by jyasskin** [Polymer/polymer#1809]
See http://plnkr.co/edit/DCLtFWbGN0RrIDVSikrB?p=preview for an example. Only the first `::shadow` or `/deep/` is getting removed from the style rules. On Chrome (with native support for `/deep/`, that means the background color gets stuck after the first nesting level. On Firefox, both the foreground and background colors get stuck there.

```css
    li { color: red; }
    li ol::shadow li { color: blue; }
    li ol::shadow li ol::shadow li { color: green; }
    li { background-color: lightblue; }
    li /deep/ li { background-color: lightgreen; }
    li /deep/ li /deep/ li { background-color: pink; }
```
in the custom element stylesheet becomes the following in the document stylesheet:
```css
li.dom-recurse {  color: red;}
li.dom-recurse ol.dom-recurse  li {  color: blue;}
li.dom-recurse ol.dom-recurse  li ol::shadow li {  color: green;}
li.dom-recurse {  background-color: lightblue;}
li.dom-recurse   li {  background-color: lightgreen;}
li.dom-recurse   li /deep/ li {  background-color: pink;}
```
