### ISSUE TITLE
Parsing compressed CSS does not work

### ISSUE THREAD

**Issue by alefwmm** [Polymer/polymer#1927]
The parser for custom properties does not work for compressed CSS like:
```css
:host{--my-custom-color:#F00;}
```

When not compressed, it works properly:
```css
:host {
    --my-custom-color: #F00;
}
```

**Comment by YuJM** [comment]
try 
(intdex.html )
<style is="custom-style">
:root {
--my-custom-color:#F00;
}
</style>

(your custom-element )
.
.
<style>
  :host{
background-color:var(--my-custom-color);
}
</style>
..

**Comment by alefwmm** [comment]
My bad, I found what the problem really is.
When the last CSS rule is a custom variable and does not have a semi-colon, the problem happens.

This is okay:
```css
:root{--my-custom-color:#F00;}
```

This is not:
```css
:root{--my-custom-color:#F00}
```

[demo of the bug](http://alefwmm/polymer_1927/)
