### ISSUE TITLE
:host borders ?

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#2017]
http://jsbin.com/wedogi/edit?html,output

Explanation please why I have two red stripes instead of a border?

**Comment by jongeho1** [comment]
@gertcuykens  i believe elements are inline by default (0.5 style guide should mention it). I think you can do something like so:

```css
 :host{
        /* by default elements are inline */
        display:block;
        border: 2px solid red;
        border-radius: 5px;
        box-sizing: border-box;
        color:orange;
      }
```

or style the ```p``` element.

Thanks

@jongeho1
