### ISSUE TITLE
CSS variables in Polymer ignore media queries

### ISSUE THREAD

**Issue by teslayana** [Polymer/polymer#2149]
``` css
:root {
  --gap-between-cards: 16px;
}

/* Small */
@media (max-width: 600px) {
  :root {
    --gap-between-cards: 4px;
  }
}

/* Tablet+ */
@media (min-width: 601px) {
  :root {
    --gap-between-cards: 16px;
  }
}
```

Expected behaviour:
- Below 601px width: 4px
- Above 600px width: 16px

Observed behaviour:
- Below 601px width: 16px
- Above 600px width: 16px

If I switch those values around to:

``` css
/* Small */
@media (max-width: 600px) {
  :root {
    --gap-between-cards: 16px;
  }
}

/* Tablet+ */
@media (min-width: 601px) {
  :root {
    --gap-between-cards: 4px;
  }
}
```

Expected behaviour:
- Below 601px width: 16px
- Above 600px width: 4px

Observed behaviour:
- Below 601px width: 4px
- Above 600px width: 4px

So it seems the last value is applied as variable value.
