### ISSUE TITLE
parenthesis "(" in custom property value causes the page fails to load

### ISSUE THREAD

**Issue by frankiefu** [Polymer/polymer#2251]
This issue only happens in #master and works fine in v1.0.9.
When I load index.html I got:
Uncaught TypeError: Cannot read property '__urlResolver' of undefined    resolve-url.html:66 

x-app.css
```CSS
:host {
  display: block;
  --x-app-background-image: url(http://placehold.it/400x300);
}

.bg {
  height: 300px;
  background-image: var(--x-app-background-image);
}
```

x-app.html
```HTML
<dom-module id="x-app">

  <link rel="import" type="css" href="x-app.css">

  <template>

    <div class="bg">Hello World</div>

  </template>

  <script>

    Polymer({

      is: 'x-app'

    });

  </script>

</dom-module>
```

index.html
```HTML
<!doctype html>
<html>
<head>

  <title></title>
  <meta charset="utf-8">
  <script src="../../../polymer/components/webcomponentsjs/webcomponents-lite.js"></script>
  <link rel="import" href="x-app.html">

</head>
<body>

  <x-app></x-app>

</body>
</html>
```
