### ISSUE TITLE
@apply bunch of styles for various elements

### ISSUE THREAD

**Issue by nazar-pc** [Polymer/polymer#2319]
I'd like to use normalize.css, while avoiding to patch it with `html /deep/ whatever`.
Perfect solution would be to create WebComponent and then use it inside other elements with:
```css
@apply(--normalize-css);
```
I mean right in CSS root, not in some specific selector.
In such way I can apply it only to elements I need, not literally everywhere.
It doesn't seem to be possible at the moment, but are there any plans for this?

**Comment by nazar-pc** [comment]
How to use it: for instance, I've imported component called `x-button`.
This nice button comes in red color.
I want to add to it's styles:
```css
:host([green]) {
    background: green;
}
```
So that it would be possible to use the same button as:
```html
<x-button green></x-button>
```

Currently there is no possibility to reuse it in such way other than:
```css
html /deep/ x-button[green] {
    background: green;
}
```
