### ISSUE TITLE
Custom properties cannot be set in @keyframe rules

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer#2399]
Polymer's property system currently does not allow properties to be used within @keyframe rules. These rules are ignored right now because they do not require selector modification. The custom property system should be made to account for this and allow properties to be consumed in @keyframe rules.

Simple repro: http://jsbin.com/mopuwe/edit?html,output

**Comment by notwaldorf** [comment]
Note for future-Monica and future-Steve: when this is resolved, we can fix https://github.com/PolymerElements/paper-checkbox/issues/59 (/cc @samccone)

**Comment by samccone** [comment]
:bow: :bowling:

**Comment by traviskaufman** [comment]
bump. This is blocking me from a `paper-progress` revamp.

**Comment by traviskaufman** [comment]
https://github.com/Polymer/polymer/blob/c2b7c31b8e176a642bbf81f422d19091ed80d5e3/src/lib/style-util.html#L59-L61

What the reasoning for `skipRule = true` when the style is a keyframe rule? No support yet for parsing keyframe blocks?

**Comment by cdata** [comment]
@traviskaufman Currently the parser is not distinguishing between keyframes such as

```css
@keyframes foo {
  /** Keyframe of the foo animation **/
  from {
    left: 0px;
  }
}
```

and standard selectors such as:

```css
@media all {
  /** Selector that matches <from> elements **/
  from {
    left: 0px;
  }
}
```

the side effect of which is that a keyframe will be transformed into something appropriate for a selector, but inappropriate for a keyframe block, such as:

```css
@keyframes foo {
  /** Keyframe of the foo animation **/
  from:not([style-scope]):not(.style-scope) {
    left: 0px;
  }
}
```

I'm investigating a potential quick fix to address this.
