### ISSUE TITLE
firefox doesn't play along like the others using css :unresolved ? 

### ISSUE THREAD

**Issue by gertcuykens** [Polymer/polymer#2435]
firefox doesn't like this part?

``` css
            :unresolved {
                display: flex;
                justify-content: flex-start;
                background: rgba(255,255,255,0.5);
                border: 1px dashed #ccc;
                border-radius: 5px;
                box-sizing: border-box;
            }
            :unresolved:after {
                padding: 15px;
                content: 'loading...';
                color: #ccc;
            }
```
