### ISSUE TITLE
@apply creates rules with +1 class specificity (shady dom)

### ISSUE THREAD

**Issue by zhaoz** [Polymer/polymer#2439]
If I use a @apply, the CSS  gets moved out into a separate css block with a more specific rule. This is in polymer 1.0

```CSS
:root {
  --mixin: {
    background-color: blue;
  }
}

:host {
  @apply(--mixin);
}

:host.red {
  background-color: red;
}
```

The element being styled will be blue background, even if it has the class 'red' on it.

This is non-obvious reading the code, and not the easiest to fix since you have to add junk selectors to everything to make it be more specific.

From what I can tell the problem is two fold.
1. @apply creates a separate css block with a selector that is more specific.
2. The extra css block is appended at the end, which means although it has the same specificity, the CSS cascade overrides the :host.red rules.
