### ISSUE TITLE
Allow for explicit CSS mixin inheritience when re-defining a mixin

### ISSUE THREAD

**Issue by bendavis78** [Polymer/polymer#2487]
Take the following use case:

We have a big theme file that defines some mixins for standard paper-\* elements:

``` css
:root {
  --paper-dropdown-menu-icon: {
    color: var(--some-theme-color);
  };
}
```

Now, let's say I have a custom element called `my-custom-form` that needs to make a padding tweak to dropdown icons, and defines the following in its stylesheet:

``` css
:host {
  --paper-dropdown-menu-icon: {
    padding-right: 12px;
  };
}
```

This, of course, will wipe out whatever CSS properties were defined in the global theme. The common workaround to this is for custom elements to something like this:

``` css
:host {
  --paper-dropdown-menu-icon: {
    padding-right: 12px;
    @apply(--my-custom-form-paper-dropdown-menu-icon);
  };
}
```

But then the theme author has to add the new mixin to the theme file, and things start getting ugly:

``` css
:root {
  --paper-dropdown-menu-icon: {
    color: var(--some-theme-color);
  };
  --my-custom-form-paper-dropdown-menu: {
    color: var(--some-theme-color);
  };
}
```

Ideally, an element developer would be able to decide explicitly whether a mixin should extend the currently defined mixin, or just override it. My proposal would look like this:

``` css
:host {
  --paper-dropdown-menu-icon: {
    @apply();
    padding-right: 12px;
  }
}
```

Calling `@apply()` without arguments would apply rules from the currently defined mixin (think `super()` in python).

**Comment by nazar-pc** [comment]
I do not like this particular syntax, but :+1: for such feature, would be nice to have.
Probably, this way might be more explicit:
```css
:host {
  --paper-dropdown-menu-icon: {
    @apply(--paper-dropdown-menu-icon);
    padding-right: 12px;
  }
}
```

If think logically, `--paper-dropdown-menu-icon` when we use it exists as declaration for some element higher in DOM tree, so we can use it without issues (literally we just extend it for current part of DOM tree).

But I guess, for this feature to be implemented it should be suggested and added to standard proposal: https://tabatkins.github.io/specs/css-apply-rule/
