### ISSUE TITLE
:host styles have specificity issues vs. *

### ISSUE THREAD

**Issue by notwaldorf** [Polymer/polymer#2558]
If in my demo I have
```css
<style is="custom-style">
  * { box-sizing: border-box; }
</style>
```

And in my element that I import in this demo I have:
```css
<style>
  :host { box-sizing: content-box; }
</style>
```

The `*` style always wins (the dev tools actually interprets it as `*:not([style-scope]):not(.style-scope)`), which means you need to pepper the `:host` styles with `!important`.

**Comment by nazar-pc** [comment]
@notwaldorf, it works the same way under native Shadow DOM.
Styles applied to element from the outside have higher priority, nothing wrong here.
While nesting element inside other element should not propagate styles, and it works exactly the way it should:
```html
<style>
	* { border: 1px solid red; }
</style>
<dom-module id="x-host">
	<template>
		<p></p>
		<x-nested></x-nested>
		<p></p>
	</template>
</dom-module>
<dom-module id="x-nested">
	<template>
		<style>
			:host { border: 1px solid blue; }
		</style>
	</template>
</dom-module>
<script>
	Polymer({is: 'x-host'});
	Polymer({is: 'x-nested'});
</script>
<x-host></x-host>
```
`x-host::shadow > x-nested` in this example have `blue` border, not `red` as everything else.

**Comment by azakus** [comment]
Yep, `:host` always loses, because it is meant to give "default" styling, like the User-Agent stylesheet, like
```css
div {
  display: block
}
```
