### ISSUE TITLE
Applied styles couldn't be overridden.

### ISSUE THREAD

**Issue by nanowang** [Polymer/polymer#2739]
Say I imported `paper-styles` and got the following styles in my own element

```css
:host p.some-p {
  @apply(--paper-font-headline);
  font-weight: bold;
}
```

And the `font-weight` wont be overridden to bold as expected. Looks like stamping and applying the styles via `@apply` wont consider the order of styles in the same block.
