### ISSUE TITLE
CSS variables doesn't work inside the @media

### ISSUE THREAD

**Issue by yordis** [Polymer/polymer#2745]
The following code doesn't work.

```CSS

--desktop-breakpoint: 840px;

@media (min-width: var(--desktop-breakpoint)) {
      :host([hide-on*="desktop"]) { display: none; }
}
```
