### ISSUE TITLE
CSS variables doesn't work properly

### ISSUE THREAD

**Issue by yordis** [Polymer/polymer#2746]
I have this CSS inside my element
```CSS
:host {
      --default-width: 25%;
      width: var(--default-width);
      ...
    }


@media (min-width: 840px) {
     :host([desktop="1"]) { width: 8.3333333333%; }
}
```

This is the output of my CSS which is wrong, because Polymer extract the section where I did `      width: var(--default-width);` and create a new tag with that CSS output. My `media query` doesn't work because that selector overrides the `media query` one.
![screen shot 2015-11-16 at 4 22 13 pm](https://cloud.githubusercontent.com/assets/4237280/11195616/ca3ce63c-8c80-11e5-86e5-ccc4c83d9328.png)

The cascade is wrong.
<img width="201" alt="screen shot 2015-11-16 at 4 21 36 pm" src="https://cloud.githubusercontent.com/assets/4237280/11195642/fbe72e4a-8c80-11e5-9b99-25d440006633.png">
