### ISSUE TITLE
Error in rewritten selector when styling distributed children (::content)

### ISSUE THREAD

**Issue by MeTaNoV** [Polymer/polymer#3059]
Hi,

I started a `<gold-password-input>` which is without surprise based on a `<paper-input-container>` and includes an additional `addon` that takes care of displaying the strength score of the password.
You could find the page of the element (and the demo) [here](http://metanov.github.io/gold-password-input/).
Depending on the strength score, I apply different classes on a subelement of the strength addon element to change the text color. The different classes are correctly applied but when the input has focus, the selector rule defined in the <paper-input-container> is overriding the local DOM selector.
See the following screenshot that you can reproduce on the demo page of the component.

#### Non Working
![2015-11-19_20-55-55](https://cloud.githubusercontent.com/assets/11166016/11286573/eee72ad2-8f15-11e5-9a95-10f89cc03d0f.png)
![2015-11-19_20-55-07](https://cloud.githubusercontent.com/assets/11166016/11286612/3983be02-8f16-11e5-8f0b-3307298ad716.png)

#### Working (because the elements have two classes...)
![2015-11-19_20-54-43](https://cloud.githubusercontent.com/assets/11166016/11286851/b105c3e8-8f17-11e5-9f28-e2386e2f26f0.png)
![2015-11-19_20-51-15](https://cloud.githubusercontent.com/assets/11166016/11286619/44020500-8f16-11e5-86b8-7d1b2a1a97a5.png)

#### Working (when the input looses focus)
![2015-11-19_20-56-17](https://cloud.githubusercontent.com/assets/11166016/11286628/52f948fc-8f16-11e5-95e6-64f654ec1494.png)
![2015-11-19_20-56-39](https://cloud.githubusercontent.com/assets/11166016/11286629/5612dec2-8f16-11e5-8b59-5f87da919f2d.png)

This is the way `<paper-input-container>` defines the CSS with the highlighted addon:
```css
      .add-on-content.is-highlighted ::content * {
        color: var(--paper-input-container-focus-color, --default-primary-color);
      }
```
This is the way I define my CSS on the addon:
```css
      .None {
        color: var(--gold-password-input-strength-meter-none-color, --paper-grey-700);
      }
      .Very.Weak {
        color: var(--gold-password-input-strength-meter-veryweak-color, --paper-red-700);
      }
      .Weak {
        color: var(--gold-password-input-strength-meter-weak-color, --paper-orange-700);
      }
      .Medium {
        color: var(--gold-password-input-strength-meter-medium-color, --paper-yellow-700);
      }
      .Strong {
        color: var(--gold-password-input-strength-meter-strong-color, --paper-blue-700);
      }
      .Very.Strong {
        color: var(--gold-password-input-strength-meter-verystrong-color, --paper-green-700);
      }
```

Any idea why this happens? 
Cheers,
Pascal aka MeTaNoV

**Comment by arthurevans** [comment]
The `paper-input-container` rule has two classes, so I'd expect that to trump the single selector (`.Weak`). Have you tried just adding another class (or an ID) to the strength meter, so it's

    .stength-mether.Weak 

or:

    #meter.Weak

**Comment by MeTaNoV** [comment]
Sound weird to have to do this... but I suppose it will do the job! As a work around I used myself `!important` but I am not sure 100% it should be this way... Thanks for your tip @arthurevans !

**Comment by MeTaNoV** [comment]
Shouldn't the definition of `<paper-input-container` selector remove `::content` since it uses `*` selector?

**Comment by MeTaNoV** [comment]
Also imagine a case where I defined the following selector in `my-element` 
```
.class1 .class2 ::content * { ...some style }
```
then a content `sub-element` styling has no way to win the specificity race against it? Doesn't this break somehow the styling encapsulation we want or I misunderstand the problem?

**Comment by MeTaNoV** [comment]
@arthurevans , after investigation, I found out this in the [Polymer Documentation about Styling](https://www.polymer-project.org/1.0/docs/devguide/styling.html#styling-distributed-children-content):

"
Under shady DOM, the `<content>` tag doesn’t appear in the DOM tree. Styles are rewritten to remove the `::content` pseudo-element, **and any combinator immediately to the left** of `::content`.
"

This style rewriting is in line with my previous comment, and is not properly done in my example.
In my case:
```css
      .add-on-content.is-highlighted ::content * {
        color: var(--paper-input-container-focus-color, --default-primary-color);
      }
```
is rewritten to
`.paper-input-container-0 .add-on-content.is-highlighted.paper-input-container *`
instead of
`.add-on-content.is-highlighted.paper-input-container *`
which will solve therefore the issue!

@ebidel I browsed the opened issues w/o finding any good similar candidate, is it an issue you know of?
