### ISSUE TITLE
Extend CSS shimming capabilities

### ISSUE THREAD

**Issue by jouni** [Polymer/polymer#3314]
Would it be possible to open up the current CSS shimming for extension/customization?

Namely, I’m looking for a way to add the [CSS color() function](https://drafts.csswg.org/css-color-4/#modifying-colors) capabilities to Polymer styling.

**Example**: styling a gradient button, where setting one custom color property adjusts other properties accordingly:

In `custom-button.html`:

``` css
:host {
  --custom-button-background-color: #00b4f0;

  background: linear-gradient(
    color( var(--custom-button-background-color) tint(10%) ),
    color( var(--custom-button-background-color) shade(10%) )
  );

  color: color( var(--custom-button-background-color) contrast(100%) );
}
```

I’m not expecting this to be of any priority right now, so I would also be very grateful for any pointers where to look in the code so I could possibly prototype this myself.
