### ISSUE TITLE
Local DOM rules with multiple selectors are shimmed incorrectly

### ISSUE THREAD

**Issue by arturparkhisenko** [Polymer/polymer#3555]
### Description

Shared styles to global scope if we used multiple selectors (one usual, and one with `::content`) in one CSS rule.
Or i have to write only selectors `::content selector` if i'll use dynamically added content (elements).
Maybe related to this fix https://github.com/Polymer/polymer/commit/d9f3dda
Also it's only for `shady` DOM ;)

#### Live Demo

http://plnkr.co/edit/9RFUOiZNOsL0WNJ16iqT?p=preview

#### Steps to Reproduce

1. Use/Write multiple selectors in one rule, in second selector without `:host` before `::content`.
  - example: `button, ::content button {}`
2. You'll see affected usual non-components elements and dynamically added elements inside components.

#### Expected Results

```css
button.custom-element-2:hover,  custom-element-2 button:hover {
  background-color: cadetblue;
}
```

#### Actual Results

```css
button.custom-element-2:hover,  button:hover {
  background-color: cadetblue;
}
```

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions

- Polymer: v1.4.0
- webcomponents: v0.7.20
