### ISSUE TITLE
custom properties defined in `:host` don't reapply if the rule is inside a media query.

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer#3696]
### Description

Say you have:
```css
:host {
  display: block;
  --color: red;
}

div {
  color: var(--color);  
}

@media (max-width: 800px) {
  :host {
    --color: blue;
  }
}
```

#### Live Demo

https://jsbin.com/mekike/edit?html,output

#### Expected Results
 I'd expect the div's color to be blue if the media query is matching.

#### Actual Results
The div's color remains red unless you refresh the browser.

### Browsers Affected
- All browsers

### Versions

- Polymer:  master and `useNativeCSSProperties = false`
