### ISSUE TITLE
Issues with mixins having `!important` properties when using native custom properties.

### ISSUE THREAD

**Issue by blasten** [Polymer/polymer#3700]
Say I have:

``` js
:host {
  --a: 10px;
  --b: {
    width: var(--a) !important;
  };
}
div {
  @apply(--b);
}
```
#### Expected Results

The mixin transformer to native custom properties should preserve the `!important` property

``` css
div {
  width: var(--b_-_width) !important;
}
```
#### Actual Results

The mixin transformer to native custom properties generates the following rule (moreless):

``` css
div {
  width: var(--b_-_width); /* No !important */
}
```
### Browsers Affected

All browsers that support this setup.
### Versions
- Polymer: master branch and `useNativeCSSProperties: true`
