### ISSUE TITLE
2.0-preview error in composition of css mixins

### ISSUE THREAD

**Issue by mkazlauskas** [Polymer/polymer#4118]
### Description
Can't define css mixin that is already defined.

### Expected outcome
No error

### Actual outcome
![error](https://i.imgur.com/IxVABJx.png)

### Steps to reproduce
1. checkout paper-dropdown-menu 2.0-preview
2. define css mixin under `paper-dropdown-menu` in `demo/index.html`:

  ```css
  paper-dropdown-menu {
    width: 200px;
    margin-right: 20px;
    --paper-input-container-input: {
      text-align: center;
    };
  }
  ```
3. `$ polymer serve`
4. open demo page - error is thrown
5. change order in which mixins are applied in `paper-dropdown-menu-shared-styles.html`:

  ```css
      @apply --paper-dropdown-menu;
      --paper-input-container-input: {
        overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis;
        max-width: 100%;
        box-sizing: border-box;
        cursor: pointer;
       };
  ```
6. refresh demo page - error is no longer thrown

### Browsers Affected
Linux Chrome 54.0.2840.71 (64-bit)
Not sure about any other browsers

### Versions
- Polymer: 2.0-preview
- webcomponents: v1
