### ISSUE TITLE
Using a :host.class selector with CSS variables

### ISSUE THREAD

**Issue by johnpryan** [Polymer/polymer#4218]
### Description

I am trying to use a CSS variable in the following selector:

```css
:host.iron-selected {
  background-color: var(--my-color);
}
```
where `--my-color` is defined in an ancestor component.  This only seems to work with the following:

```
:host {
  --my-color-computed: var(--my-color);
}
:host.iron-selected {
  background-color: var(--my-color-computed);
}
```
I am using polymer.dart.

### Versions

- Polymer: polymer.dart 1.0.0-rc.19
- webcomponents: v0.7.23
