### ISSUE TITLE
Polymer 1 shady CSS parsing bug

### ISSUE THREAD

**Issue by notwaldorf** [Polymer/polymer#4248]
First of all, I am sorry for what you're about to read. The context is that `textarea` has a weird padding on iOS (and only iOS; not even on desktop safari), so we need to apply a style and undo it on all the other browsers. Yes, you can cry now.

These are the new selectors that we need to be able to add. The last 3 make the parser barf, with errors such as 
```
Uncaught DOMException: Failed to execute 'matches' on 'Element': '_:not([style-scope]):not(.style-scope):-ms-fullscreen,html iron-autogrow-textarea.fixed:not([style-scope]):not(.style-scope)' is not a valid selector.
````

The selectors:
```css
      /* Undo the margin on non-iOS Safari and Chrome (=.=). This hack is taken from
       * http://browserstrangeness.bitbucket.org/css_hacks.html#webkit
       * and I'm sure one day will end, but for now, here we are.
       */
      _:-webkit-full-screen-ancestor, :root iron-autogrow-textarea.fixed {
        --iron-autogrow-textarea-margin-left: 0;
      }

      /* Undo on Edge */
      _:-ms-lang(x), _:-webkit-full-screen, iron-autogrow-textarea.fixed {
        --iron-autogrow-textarea-margin-left: 0;
      }

      /* Undo on IE. Safari, this is why we can't have nice things. */
      _:-ms-fullscreen, :root iron-autogrow-textarea.fixed {
        --iron-autogrow-textarea-margin-left: 0;
      }

      /* Undo on FF */
      @-moz-document url-prefix() {
        iron-autogrow-textarea.fixed {
          --iron-autogrow-textarea-margin-left: 0;
        }
      }
```

You can pull this PR to test it: https://github.com/PolymerElements/iron-autogrow-textarea/pull/94

Also, sorry.
