### ISSUE TITLE
[Shady CSS 1 & 2] CSS Custom properties with ; (base64, URI) gets corrupted

### ISSUE THREAD

**Issue by tomalec** [Polymer/polymer#4288]
#### Live Demo
https://jsbin.com/horimo/edit?html,output
(jsbin fails due to some cors issues)

Reference example;
https://jsbin.com/dovuli/edit?html,output

#### Steps to Reproduce

1. Create `my-element`
2. Attach custom property to the elements shadow dom scope:
   ```css
   :root {
       --icon-svg: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiIgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0Ij4gICAgPHBhdGggc3R5bGU9InRleHQtaW5kZW50OjA7dGV4dC1hbGlnbjpzdGFydDtsaW5lLWhlaWdodDpub3JtYWw7dGV4dC10cmFuc2Zvcm06bm9uZTtibG9jay1wcm9ncmVzc2lvbjp0YjstaW5rc2NhcGUtZm9udC1zcGVjaWZpY2F0aW9uOkJpdHN0cmVhbSBWZXJhIFNhbnMiIGQ9Ik0gNiA0IEwgNiA1IEwgNiAyNyBMIDYgMjggTCA3IDI4IEwgMTcuMDkzNzUgMjggQyAxOC40ODEwNTIgMzAuMzg1NjMxIDIxLjA1MDk0MSAzMiAyNCAzMiBDIDI4LjQwNjQzMyAzMiAzMiAyOC40MDY0MzMgMzIgMjQgQyAzMiAyMC4yODg2MSAyOS40MzcxMzQgMTcuMTc3ODE3IDI2IDE2LjI4MTI1IEwgMjYgNSBMIDI2IDQgTCAyNSA0IEwgNyA0IEwgNiA0IHogTSA4IDYgTCAyNCA2IEwgMjQgMTEgTCA4IDExIEwgOCA2IHogTSA4IDEzIEwgMjQgMTMgTCAyNCAxNiBDIDIxLjQ4MTcyNCAxNiAxOS4yNDk1IDE3LjE3MTYzNyAxNy43ODEyNSAxOSBMIDggMTkgTCA4IDEzIHogTSAyNCAxOCBDIDI3LjMyNTU1MyAxOCAzMCAyMC42NzQ0NDcgMzAgMjQgQyAzMCAyNy4zMjU1NTMgMjcuMzI1NTUzIDMwIDI0IDMwIEMgMjAuNjc0NDQ3IDMwIDE4IDI3LjMyNTU1MyAxOCAyNCBDIDE4IDIwLjY3NDQ0NyAyMC42NzQ0NDcgMTggMjQgMTggeiBNIDggMjEgTCAxNi41OTM3NSAyMSBDIDE2LjIxMjU5NyAyMS45MzEzNzYgMTYgMjIuOTM0MTUyIDE2IDI0IEMgMTYgMjQuNjk1MDQzIDE2LjExMzM0NyAyNS4zNTYzMTggMTYuMjgxMjUgMjYgTCA4IDI2IEwgOCAyMSB6IE0gMjcuMjgxMjUgMjEuMjgxMjUgTCAyNCAyNC41NjI1IEwgMjEuNzE4NzUgMjIuMjgxMjUgTCAyMC4yODEyNSAyMy43MTg3NSBMIDIzLjI4MTI1IDI2LjcxODc1IEwgMjQgMjcuNDA2MjUgTCAyNC43MTg3NSAyNi43MTg3NSBMIDI4LjcxODc1IDIyLjcxODc1IEwgMjcuMjgxMjUgMjEuMjgxMjUgeiIgY29sb3I9IiMwMDAiIG92ZXJmbG93PSJ2aXNpYmxlIiBmb250LWZhbWlseT0iQml0c3RyZWFtIFZlcmEgU2FucyIvPjwvc3ZnPg==);
       --icon-svg-2: url(data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiIgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0Ij4gICAgPHBhdGggc3R5bGU9InRleHQtaW5kZW50OjA7dGV4dC1hbGlnbjpzdGFydDtsaW5lLWhlaWdodDpub3JtYWw7dGV4dC10cmFuc2Zvcm06bm9uZTtibG9jay1wcm9ncmVzc2lvbjp0YjstaW5rc2NhcGUtZm9udC1zcGVjaWZpY2F0aW9uOlNhbnMiIGQ9Ik0gNSA1IEwgNSA2IEwgNSAxMCBMIDUgMTEgTCA2IDExIEwgMjYgMTEgTCAyNyAxMSBMIDI3IDEwIEwgMjcgNiBMIDI3IDUgTCAyNiA1IEwgNiA1IEwgNSA1IHogTSA3IDcgTCAyNSA3IEwgMjUgOSBMIDcgOSBMIDcgNyB6IE0gNSAxMyBMIDUgMTQgTCA1IDE4IEwgNSAxOSBMIDYgMTkgTCAyNiAxOSBMIDI3IDE5IEwgMjcgMTggTCAyNyAxNCBMIDI3IDEzIEwgMjYgMTMgTCA2IDEzIEwgNSAxMyB6IE0gNyAxNSBMIDI1IDE1IEwgMjUgMTcgTCA3IDE3IEwgNyAxNSB6IE0gNSAyMSBMIDUgMjIgTCA1IDI2IEwgNSAyNyBMIDYgMjcgTCAyNiAyNyBMIDI3IDI3IEwgMjcgMjYgTCAyNyAyMiBMIDI3IDIxIEwgMjYgMjEgTCA2IDIxIEwgNSAyMSB6IE0gNyAyMyBMIDI1IDIzIEwgMjUgMjUgTCA3IDI1IEwgNyAyMyB6IiBjb2xvcj0iIzAwMCIgb3ZlcmZsb3c9InZpc2libGUiIGZvbnQtZmFtaWx5PSJTYW5zIi8+PC9zdmc+);
   }
   .icon {
       background-image: var(--icon-svg);
   }
   ```
3. Stamp `my-element`

#### Expected Results
Background image is resolved and rendered
![fireshot capture 017 - js bin - collaborative javascript debuggin_ - https___jsbin com_dovuli_4_edit](https://cloud.githubusercontent.com/assets/17435/22556134/6b3026ba-e966-11e6-84da-0ab4a66f08f2.png)

#### Actual Results
CSS gets corrupted:
```css
:host > * {
  ;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiIgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0Ij4gICAgPHBhdGggc3R5bGU9InRleHQtaW5kZW50OjA7dGV4dC1hbGlnbjpzdGFydDtsaW5lLWhlaWdodDpub3JtYWw7dGV4dC10cmFuc2Zvcm06bm9uZTtibG9jay1wcm9ncmVzc2lvbjp0YjstaW5rc2NhcGUtZm9udC1zcGVjaWZpY2F0aW9uOkJpdHN0cmVhbSBWZXJhIFNhbnMiIGQ9Ik0gNiA0IEwgNiA1IEwgNiAyNyBMIDYgMjggTCA3IDI4IEwgMTcuMDkzNzUgMjggQyAxOC40ODEwNTIgMzAuMzg1NjMxIDIxLjA1MDk0MSAzMiAyNCAzMiBDIDI4LjQwNjQzMyAzMiAzMiAyOC40MDY0MzMgMzIgMjQgQyAzMiAyMC4yODg2MSAyOS40MzcxMzQgMTcuMTc3ODE3IDI2IDE2LjI4MTI1IEwgMjYgNSBMIDI2IDQgTCAyNSA0IEwgNyA0IEwgNiA0IHogTSA4IDYgTCAyNCA2IEwgMjQgMTEgTCA4IDExIEwgOCA2IHogTSA4IDEzIEwgMjQgMTMgTCAyNCAxNiBDIDIxLjQ4MTcyNCAxNiAxOS4yNDk1IDE3LjE3MTYzNyAxNy43ODEyNSAxOSBMIDggMTkgTCA4IDEzIHogTSAyNCAxOCBDIDI3LjMyNTU1MyAxOCAzMCAyMC42NzQ0NDcgMzAgMjQgQyAzMCAyNy4zMjU1NTMgMjcuMzI1NTUzIDMwIDI0IDMwIEMgMjAuNjc0NDQ3IDMwIDE4IDI3LjMyNTU1MyAxOCAyNCBDIDE4IDIwLjY3NDQ0NyAyMC42NzQ0NDcgMTggMjQgMTggeiBNIDggMjEgTCAxNi41OTM3NSAyMSBDIDE2LjIxMjU5NyAyMS45MzEzNzYgMTYgMjIuOTM0MTUyIDE2IDI0IEMgMTYgMjQuNjk1MDQzIDE2LjExMzM0NyAyNS4zNTYzMTggMTYuMjgxMjUgMjYgTCA4IDI2IEwgOCAyMSB6IE0gMjcuMjgxMjUgMjEuMjgxMjUgTCAyNCAyNC41NjI1IEwgMjEuNzE4NzUgMjIuMjgxMjUgTCAyMC4yODEyNSAyMy43MTg3NSBMIDIzLjI4MTI1IDI2LjcxODc1IEwgMjQgMjcuNDA2MjUgTCAyNC43MTg3NSAyNi43MTg3NSBMIDI4LjcxODc1IDIyLjcxODc1IEwgMjcuMjgxMjUgMjEuMjgxMjUgeiIgY29sb3I9IiMwMDAiIG92ZXJmbG93PSJ2aXNpYmxlIiBmb250LWZhbWlseT0iQml0c3RyZWFtIFZlcmEgU2FucyIvPjwvc3ZnPg==');base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAzMiAzMiIgd2lkdGg9IjY0IiBoZWlnaHQ9IjY0Ij4gICAgPHBhdGggc3R5bGU9InRleHQtaW5kZW50OjA7dGV4dC1hbGlnbjpzdGFydDtsaW5lLWhlaWdodDpub3JtYWw7dGV4dC10cmFuc2Zvcm06bm9uZTtibG9jay1wcm9ncmVzc2lvbjp0YjstaW5rc2NhcGUtZm9udC1zcGVjaWZpY2F0aW9uOlNhbnMiIGQ9Ik0gNSA1IEwgNSA2IEwgNSAxMCBMIDUgMTEgTCA2IDExIEwgMjYgMTEgTCAyNyAxMSBMIDI3IDEwIEwgMjcgNiBMIDI3IDUgTCAyNiA1IEwgNiA1IEwgNSA1IHogTSA3IDcgTCAyNSA3IEwgMjUgOSBMIDcgOSBMIDcgNyB6IE0gNSAxMyBMIDUgMTQgTCA1IDE4IEwgNSAxOSBMIDYgMTkgTCAyNiAxOSBMIDI3IDE5IEwgMjcgMTggTCAyNyAxNCBMIDI3IDEzIEwgMjYgMTMgTCA2IDEzIEwgNSAxMyB6IE0gNyAxNSBMIDI1IDE1IEwgMjUgMTcgTCA3IDE3IEwgNyAxNSB6IE0gNSAyMSBMIDUgMjIgTCA1IDI2IEwgNSAyNyBMIDYgMjcgTCAyNiAyNyBMIDI3IDI3IEwgMjcgMjYgTCAyNyAyMiBMIDI3IDIxIEwgMjYgMjEgTCA2IDIxIEwgNSAyMSB6IE0gNyAyMyBMIDI1IDIzIEwgMjUgMjUgTCA3IDI1IEwgNyAyMyB6IiBjb2xvcj0iIzAwMCIgb3ZlcmZsb3c9InZpc2libGUiIGZvbnQtZmFtaWx5PSJTYW5zIi8+PC9zdmc+');
}
```

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Edge
- [x] Safari 9
- [x] Safari 8
- [x] IE 11

### Versions

- Polymer: v1.7.1
- webcomponents: v0.7.23

### Investigations
It's pretty awkward, that it happens in Chrome which supports Shadow DOM and custom properties.

I suspect it's a bug in regexp at https://github.com/Polymer/polymer/blob/v1.7.1/polymer.html#L3487
From what I can see `/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:([^;{]*)|{([^}]*)})(?:(?=[;\s}])|$)/gi`
https://regexper.com/#%2F(%3F%3A%5E%7C%5B%3B%5Cs%7B%5D%5Cs*)(--%5B%5Cw-%5D*%3F)%5Cs*%3A%5Cs*(%3F%3A(%5B%5E%3B%7B%5D*)%7C%7B(%5B%5E%7D%5D*)%7D)(%3F%3A(%3F%3D%5B%3B%5Cs%7D%5D)%7C%24)%2Fgi
Totally disregards the fact that there could be `;` in parenthesis/quote which should not terminate parser.
