### ISSUE TITLE
Toolbar crops descenders

### ISSUE THREAD

**Issue by sk-** [Polymer/polymer#4300]
### Description
Letters with descenders are cropped in the toolbar even with the default settings.

#### Live Demo
https://jsbin.com/vaxazitivo/edit?html,console,output

<img width="613" alt="screen shot 2017-02-09 at 11 24 51 pm" src="https://cloud.githubusercontent.com/assets/911768/22783640/d2a26d7a-ef20-11e6-9c5a-18dcac036f37.png">

#### Expected Results
The lowercase `g` is fully visible.

#### Actual Results
The `g` is cropped.

### Workaround
```css
paper-toolbar {
      --paper-toolbar-title: {
        overflow: visible;
      };
    }
```

### Browsers Affected
- [X] Chrome
- [ ] Firefox
- [ ] Edge
- [X] Safari 10
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: v1.8.0
- webcomponents: v0.7.4
