### ISSUE TITLE
QUESTION: style :host depending on html attributes

### ISSUE THREAD

**Issue by iSuslov** [Polymer/polymer#4714]
Is it possible inside shadow dom make something like this:

```
<template>
<style>
html[data-platform*='Mozilla']:host{

}
....
```

**Comment by web-padawan** [comment]
Consider using CSS variables for that, e. g.
```css
html {
  --theme-color: green;
}

html[data-platform*='Mozilla'] {
  --theme-color: red;
}
```
and then just do this:
```css
:host {
  display: block;
  color: var(--theme-color);
}
```

You can only do it like this. There used to be a `:host-context` selector created to propagate styling from outwards, but it is deprecated due to Safari disagreement.
