### ISSUE TITLE
Specifity of ::slotted() is greater than :host

### ISSUE THREAD

**Issue by mindthetic** [Polymer/polymer#5106]
I'm using Polymer 2.0 and I've noticed that if you declare styles inside a component which use the `:slotted()` selector then styles applied by any child components which are uses inside that component cannot be overridden using `:host`.

```css
/* Parent component */
:slotted(*) {
    color: green;
}

/* Child component */
:host {
    color: red;
}
```

I would expect the child component's text to be red, but it is in fact green.

Is this the correct behaviour?
