### ISSUE TITLE
Minor Duplication: unnecessary core-icon-button declaration block to style the fill color of the favorite icon 

### ISSUE THREAD

**Issue by lozandier** [Polymer/polymer#570]
For some reason, two declarations blocks were used to style `core-icon-button` instead of one. If there was an explicit reason for this, it remained unaddressed. 

If I'm correct there wasn't a strong reason for the second declaration block, it may be better to have the style code snippet presented similar to the code snippet below this paragraph: 

``` scss
 core-icon-button {
    position: absolute;
    top: 3px;
    right: 3px;
    fill: #636363;
  }

  :host([favorite]) core-icon-button {
    fill: #da4336;
 }

```
