### ISSUE TITLE
::content polyfill for VanillaJS Templates and Custom Elements

### ISSUE THREAD

**Issue by tomalec** [Polymer/polymer#582]
It seems that 

``` css
polyfill-next-selector { content: ':host #myId' }
```

Does not work (in IE) for VanillaJS `<template>`s and Custom Elements.

For `<polymer-element>` it works fine: http://codepen.io/robdodson/pen/FokEw/, but for some reason when I try to do the same for :icecream: it doesn't http://codepen.io/tomalec/pen/apqgr

`shim-shadowdom` attribute also does not help.

Is there any workaround, or am I using it wrong?
