### ISSUE TITLE
Step-1 of tutorial instructions are missing vital CSS

### ISSUE THREAD

**Issue by calvinkhuang** [Polymer/polymer#622]
The following CSS is in /step-1/index.html of the Polymer tutorial but not mentioned in the directions for that step of the tutorial:

``` css
core-header-panel {
    height: 100%;
    overflow: auto;
    -webkit-overflow-scrolling: touch; 
}
core-toolbar {
    background: #03a9f4;
    color: white;
}
#tabs {
    width: 100%;
    margin: 0;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
```

Without it, the page stays blank.
